apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

sortOptions:
  order: legacy
  legacySortOptions:
    orderFirst:
    - Namespace
    - ResourceQuota
    - StorageClass
    - CustomResourceDefinition
    - MutatingWebhookConfiguration
    - ServiceAccount
    - PodSecurityPolicy
    - Role
    - ClusterRole
    - RoleBinding
    - ClusterRoleBinding
    - ConfigMap
    - Secret
    - Endpoints
    - Service
    - LimitRange
    - PriorityClass
    - PersistentVolume
    - PersistentVolumeClaim
    - Deployment
    - StatefulSet
    - CronJob
    - PodDisruptionBudget
    orderLast:
    - ValidatingWebhookConfiguration

resources:
# Cert-Manager
- ../../manifests/common/cert-manager/cert-manager/base
- ../../manifests/common/cert-manager/kubeflow-issuer/base
# Istio
- ../../manifests/common/istio-1-17/istio-crds/base
- ../../manifests/common/istio-1-17/istio-namespace/base
- ../../manifests/common/istio-1-17/istio-install/base
# OIDC Authservice
- ../../manifests/common/oidc-client/oidc-authservice/base
# Dex
- ../../manifests/common/dex/overlays/istio
# KNative
- ../../manifests/common/knative/knative-serving/overlays/gateways
- ../../manifests/common/knative/knative-eventing/base
- ../../manifests/common/istio-1-17/cluster-local-gateway/base
# Kubeflow namespace
- ../../manifests/common/kubeflow-namespace/base
# Kubeflow Roles
- ../../manifests/common/kubeflow-roles/base
# Kubeflow Istio Resources
- ../../manifests/common/istio-1-17/kubeflow-istio-resources/base


# Kubeflow Pipelines
- ../../manifests/apps/pipeline/upstream/env/cert-manager/platform-agnostic-multi-user
# Katib
- ../../manifests/apps/katib/upstream/installs/katib-with-kubeflow
# Central Dashboard
- ../../manifests/apps/centraldashboard/upstream/overlays/kserve
# Admission Webhook
- ../../manifests/apps/admission-webhook/upstream/overlays/cert-manager
# Jupyter Web App
- ../../manifests/apps/jupyter/jupyter-web-app/upstream/overlays/istio
# Notebook Controller
- ../../manifests/apps/jupyter/notebook-controller/upstream/overlays/kubeflow
# Profiles + KFAM
- ../../manifests/apps/profiles/upstream/overlays/kubeflow
# PVC Viewer
- ../../manifests/apps/pvcviewer-controller/upstream/base/
# Volumes Web App
- ../../manifests/apps/volumes-web-app/upstream/overlays/istio
# Tensorboards Controller
-  ../../manifests/apps/tensorboard/tensorboard-controller/upstream/overlays/kubeflow
# Tensorboard Web App
-  ../../manifests/apps/tensorboard/tensorboards-web-app/upstream/overlays/istio
# Training Operator
- ../../manifests/apps/training-operator/upstream/overlays/kubeflow
# User namespace
- ../user-namespace/base

# KServe
- ../../manifests/contrib/kserve/kserve
- ../../manifests/contrib/kserve/models-web-app/overlays/kubeflow
